/**
 * Guides — step-by-step, screenshot-led how-tos under Support.
 *
 * Content lives in `src/content/guides/*` as typed data (like What's new). Every
 * piece of copy may be one string for both verticals or a `ByVertical` map, so an
 * automotive owner reads "job", "vehicle", "detailer" where a trainer reads
 * "session", "client", "trainer". Business terminology tokens (`{service}`,
 * `{Services}`, `{staff}`, `{booking}`, `{record}`) are filled in at render time.
 *
 * Screenshots live under `public/guides/<vertical|shared>/<slug>/<step>.<viewport>.webp`
 * and are regenerated by `npm run guides:shots` (see scripts/guides/README.md).
 */
import type { VerticalKey } from "./verticals.ts";

export type Viewport = "desktop" | "mobile";
export const VIEWPORTS: readonly Viewport[] = ["desktop", "mobile"];

/** Copy that differs by vertical; `default` covers any vertical not named. */
export type ByVertical<T> = { default?: T } & Partial<Record<VerticalKey, T>>;
export type Copy = string | ByVertical<string>;

export type GuideCategoryKey = "setup" | "bookings" | "clients" | "money" | "messages" | "account";

export const GUIDE_CATEGORIES: readonly {
  key: GuideCategoryKey;
  label: string;
  description: Copy;
}[] = [
  {
    key: "setup",
    label: "Getting set up",
    description: {
      personal_training: "Locations, staff hours, sessions, your booking link and getting paid.",
      car_detailing: "Locations, staff hours, services, your booking page and getting paid.",
    },
  },
  {
    key: "bookings",
    label: "Bookings",
    description: {
      personal_training: "Adding, moving, editing and cancelling sessions.",
      car_detailing: "Adding, moving, editing and cancelling jobs — including multi-day work.",
    },
  },
  {
    key: "clients",
    label: "Clients",
    description: {
      personal_training: "Client records, packages and credits, and what you've sent them.",
      car_detailing: "Client records, their vehicles, follow-ups and what you've sent them.",
    },
  },
  {
    key: "money",
    label: "Payments & money",
    description: "Recording and taking payments, invoices, reports and text credits.",
  },
  {
    key: "messages",
    label: "Messages & reminders",
    description: "Confirmations, reminders and messages to clients.",
  },
  {
    key: "account",
    label: "Your account & the app",
    description: "Working offline, appearance, security, and where to find help.",
  },
];

export type GuideLink = {
  /** Route path, e.g. "/settings". */
  to: string;
  /** Search params, e.g. { tab: "payments" }. */
  search?: Record<string, string>;
  label: string;
};

export type GuideImage = {
  /** File stem, e.g. "add-booking-form". */
  name: string;
  alt: Copy;
};

export type GuideStep = {
  heading: Copy;
  /** Short markdown (GFM). Keep to a couple of sentences or a bullet list. */
  body: Copy;
  image?: GuideImage;
  link?: GuideLink;
};

export type Guide = {
  /** URL slug; unique across all guides. */
  slug: string;
  title: Copy;
  summary: Copy;
  category: GuideCategoryKey;
  verticals: readonly VerticalKey[];
  /** Rough reading time. */
  minutes: number;
  /** Both verticals look the same (e.g. settings screens): one set of images under `shared/`. */
  sharedImages?: boolean;
  steps: GuideStep[];
  /** Slugs of guides worth reading next. */
  related?: string[];
  /** Extra words search should match (synonyms, the other vertical's terms). */
  keywords?: string[];
};

export const ALL_VERTICALS: readonly VerticalKey[] = ["personal_training", "car_detailing"];

/** Pick the copy for a vertical: exact match, then `default`, then whatever is there. */
export function copy(value: Copy, vertical: VerticalKey): string {
  if (typeof value === "string") return value;
  const exact = value[vertical];
  if (exact !== undefined) return exact;
  if (value.default !== undefined) return value.default;
  for (const v of ALL_VERTICALS) {
    const any = value[v];
    if (any !== undefined) return any;
  }
  return "";
}

export type GuideTerminology = {
  staff: string;
  service: string;
  booking: string;
  client: string;
  linkedRecord: string;
};

function plural(term: string): string {
  const trimmed = term.trim();
  if (!trimmed) return trimmed;
  return /s$/i.test(trimmed) ? trimmed : `${trimmed}s`;
}

function lower(term: string): string {
  return term.trim().toLowerCase();
}

function capital(term: string): string {
  const t = term.trim();
  return t ? t.charAt(0).toUpperCase() + t.slice(1) : t;
}

/**
 * Fill business terminology into copy. `{service}` is lower case, `{Service}` capitalised,
 * `{services}` / `{Services}` plural. Same for staff, booking, client and record.
 * The "type" suffix some businesses put on their service term is dropped ("Job type" →
 * "job"), so sentences read naturally.
 */
export function applyTerminology(text: string, terminology: GuideTerminology): string {
  const base: Record<string, string> = {
    service: terminology.service.replace(/\s+type$/i, ""),
    staff: terminology.staff,
    booking: terminology.booking,
    client: terminology.client,
    record: terminology.linkedRecord,
  };
  return text.replace(/\{(service|staff|booking|client|record)(s?)\}/gi, (match, key, s) => {
    const term = base[key.toLowerCase()];
    if (term === undefined) return match;
    const word = s ? plural(term) : term;
    return key.charAt(0) === key.charAt(0).toUpperCase() ? capital(word) : lower(word);
  });
}

/** Where a step's screenshot lives for this vertical and viewport. */
export function imageSrc(
  guide: Pick<Guide, "slug" | "sharedImages">,
  image: Pick<GuideImage, "name">,
  vertical: VerticalKey,
  viewport: Viewport,
): string {
  const folder = guide.sharedImages ? "shared" : vertical;
  return `/guides/${folder}/${guide.slug}/${image.name}.${viewport}.webp`;
}

/** Every image path a guide expects to exist under `public/` (both viewports). */
export function expectedImagePaths(guide: Guide): string[] {
  const out: string[] = [];
  const verticals = guide.sharedImages ? ["shared" as const] : guide.verticals;
  for (const step of guide.steps) {
    if (!step.image) continue;
    for (const v of verticals) {
      for (const viewport of VIEWPORTS) {
        out.push(`/guides/${v}/${guide.slug}/${step.image.name}.${viewport}.webp`);
      }
    }
  }
  return out;
}

export function guidesFor(guides: readonly Guide[], vertical: VerticalKey): Guide[] {
  return guides.filter((g) => g.verticals.includes(vertical));
}

export function findGuide(guides: readonly Guide[], slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}

/** Case-insensitive match on title, summary, keywords and step headings. */
export function searchGuides(
  guides: readonly Guide[],
  vertical: VerticalKey,
  query: string,
): Guide[] {
  const q = query.trim().toLowerCase();
  const pool = guidesFor(guides, vertical);
  if (!q) return pool;
  const terms = q.split(/\s+/);
  return pool.filter((g) => {
    const haystack = [
      copy(g.title, vertical),
      copy(g.summary, vertical),
      ...(g.keywords ?? []),
      ...g.steps.map((s) => copy(s.heading, vertical)),
    ]
      .join(" ")
      .toLowerCase();
    return terms.every((t) => haystack.includes(t));
  });
}

/** Guides in a category for a vertical, keeping content order. */
export function guidesInCategory(
  guides: readonly Guide[],
  vertical: VerticalKey,
  category: GuideCategoryKey,
): Guide[] {
  return guidesFor(guides, vertical).filter((g) => g.category === category);
}

/** Problems with the guide set; empty when it is well-formed. Used by the test. */
export function validateGuides(guides: readonly Guide[]): string[] {
  const problems: string[] = [];
  const slugs = new Set<string>();
  const categories = new Set(GUIDE_CATEGORIES.map((c) => c.key));
  for (const g of guides) {
    if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(g.slug)) problems.push(`${g.slug}: slug not kebab-case`);
    if (slugs.has(g.slug)) problems.push(`${g.slug}: duplicate slug`);
    slugs.add(g.slug);
    if (g.verticals.length === 0) problems.push(`${g.slug}: no verticals`);
    if (!categories.has(g.category)) problems.push(`${g.slug}: unknown category ${g.category}`);
    if (g.steps.length === 0) problems.push(`${g.slug}: no steps`);
    if (!(g.minutes > 0)) problems.push(`${g.slug}: minutes must be positive`);
    for (const v of g.verticals) {
      if (!copy(g.title, v).trim()) problems.push(`${g.slug}: missing title for ${v}`);
      if (!copy(g.summary, v).trim()) problems.push(`${g.slug}: missing summary for ${v}`);
      g.steps.forEach((s, i) => {
        if (!copy(s.heading, v).trim()) problems.push(`${g.slug}: step ${i + 1} no heading (${v})`);
        if (!copy(s.body, v).trim()) problems.push(`${g.slug}: step ${i + 1} no body (${v})`);
        if (s.image && !copy(s.image.alt, v).trim())
          problems.push(`${g.slug}: step ${i + 1} image has no alt (${v})`);
      });
    }
    const names = new Set<string>();
    for (const s of g.steps) {
      if (!s.image) continue;
      if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(s.image.name))
        problems.push(`${g.slug}: image name "${s.image.name}" not kebab-case`);
      if (names.has(s.image.name)) problems.push(`${g.slug}: image "${s.image.name}" used twice`);
      names.add(s.image.name);
    }
  }
  for (const g of guides) {
    for (const r of g.related ?? []) {
      if (!slugs.has(r)) problems.push(`${g.slug}: related "${r}" does not exist`);
      if (r === g.slug) problems.push(`${g.slug}: related to itself`);
    }
  }
  return problems;
}
