import {
  PT_JOB_STATUSES,
  blockedTimes,
  bookings,
  business,
  clientPackages,
  clients,
  conversations,
  ledger,
  locations,
  packageDefs,
  payments,
  ptCustomRecord,
  ptCustomerFields,
  ptDashboard,
  ptTerms,
  revenueSeries,
  services,
  staff,
} from "./demo-data";
import type { IndustryDataset } from "./industry";

export const personalTrainingDataset: IndustryDataset = {
  id: "personal-training",
  label: "Personal Training",
  sector: "Fitness and coaching",
  blurb: "Sessions, packages and credits for coaches and small studios.",
  business,
  terms: ptTerms,
  jobStatuses: PT_JOB_STATUSES,
  customerFields: ptCustomerFields,
  customRecord: ptCustomRecord,
  records: [],
  resources: [],
  features: {
    mobileService: false,
    walkIns: false,
    queue: false,
    deposits: false,
    sizePricing: false,
    staffPricing: false,
    customRecords: false,
  },
  dashboard: ptDashboard,
  quickActions: [
    { id: "booking", label: "New session", icon: "CalendarPlus" },
    { id: "client", label: "Add client", icon: "UserPlus" },
    { id: "package", label: "Sell package", icon: "Package" },
    { id: "block", label: "Block availability", icon: "CalendarOff" },
  ],
  reportSections: [
    {
      title: "Attendance and retention",
      description: "How reliably clients turn up and stay",
      rows: [
        { label: "Attendance rate", value: "92%", hint: "target 95%" },
        { label: "No-show rate", value: "2.7%", hint: "5 sessions" },
        { label: "Late cancellations", value: "8", hint: "inside 24 hours" },
        { label: "90-day retention", value: "81%", hint: "up 3 points" },
      ],
    },
    {
      title: "Packages and credits",
      description: "Credit consumption and expiry risk",
      rows: [
        { label: "Credits sold", value: "214" },
        { label: "Credits used", value: "178", hint: "83% burn rate" },
        { label: "Credits expiring in 7 days", value: "9" },
        { label: "Average credits per client", value: "3.4" },
      ],
    },
  ],
  revenueSeries,
  staff,
  locations,
  services,
  packageDefs,
  clients,
  bookings,
  clientPackages,
  ledger,
  payments,
  conversations,
  blockedTimes,
};
