/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as BillingCancelRouteImport } from './routes/billing.cancel'
import { Route as BillingSetupRouteImport } from './routes/billing.setup'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ConnectRefreshBusinessIdRouteImport } from './routes/connect.refresh.$businessId'
import { Route as ConnectReturnBusinessIdRouteImport } from './routes/connect.return.$businessId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillingRoute,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => BillingRoute,
} as any)
const BillingSetupRoute = BillingSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => BillingRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BillingRoute,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRefreshBusinessIdRoute =
  ConnectRefreshBusinessIdRouteImport.update({
    id: '/refresh/$businessId',
    path: '/refresh/$businessId',
    getParentRoute: () => ConnectRoute,
  } as any)
const ConnectReturnBusinessIdRoute = ConnectReturnBusinessIdRouteImport.update({
  id: '/return/$businessId',
  path: '/return/$businessId',
  getParentRoute: () => ConnectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRouteWithChildren
  '/invite': typeof InviteRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/platform': typeof PlatformRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/setup': typeof BillingSetupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/billing/': typeof BillingIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/connect/refresh/$businessId': typeof ConnectRefreshBusinessIdRoute
  '/connect/return/$businessId': typeof ConnectReturnBusinessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRouteWithChildren
  '/invite': typeof InviteRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/platform': typeof PlatformRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/setup': typeof BillingSetupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/billing': typeof BillingIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/connect/refresh/$businessId': typeof ConnectRefreshBusinessIdRoute
  '/connect/return/$businessId': typeof ConnectReturnBusinessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRouteWithChildren
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRouteWithChildren
  '/invite': typeof InviteRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/packages': typeof PackagesRoute
  '/payments': typeof PaymentsRoute
  '/platform': typeof PlatformRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset': typeof ResetRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/setup': typeof BillingSetupRoute
  '/billing/success': typeof BillingSuccessRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/billing/': typeof BillingIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/connect/refresh/$businessId': typeof ConnectRefreshBusinessIdRoute
  '/connect/return/$businessId': typeof ConnectReturnBusinessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/connect'
    | '/invite'
    | '/locations'
    | '/login'
    | '/messages'
    | '/packages'
    | '/payments'
    | '/platform'
    | '/portal'
    | '/register'
    | '/reports'
    | '/reset'
    | '/services'
    | '/settings'
    | '/staff'
    | '/billing/cancel'
    | '/billing/setup'
    | '/billing/success'
    | '/claim/$token'
    | '/clients/$clientId'
    | '/billing/'
    | '/clients/'
    | '/connect/refresh/$businessId'
    | '/connect/return/$businessId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/connect'
    | '/invite'
    | '/locations'
    | '/login'
    | '/messages'
    | '/packages'
    | '/payments'
    | '/platform'
    | '/portal'
    | '/register'
    | '/reports'
    | '/reset'
    | '/services'
    | '/settings'
    | '/staff'
    | '/billing/cancel'
    | '/billing/setup'
    | '/billing/success'
    | '/claim/$token'
    | '/clients/$clientId'
    | '/billing'
    | '/clients'
    | '/connect/refresh/$businessId'
    | '/connect/return/$businessId'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/connect'
    | '/invite'
    | '/locations'
    | '/login'
    | '/messages'
    | '/packages'
    | '/payments'
    | '/platform'
    | '/portal'
    | '/register'
    | '/reports'
    | '/reset'
    | '/services'
    | '/settings'
    | '/staff'
    | '/billing/cancel'
    | '/billing/setup'
    | '/billing/success'
    | '/claim/$token'
    | '/clients/$clientId'
    | '/billing/'
    | '/clients/'
    | '/connect/refresh/$businessId'
    | '/connect/return/$businessId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRouteWithChildren
  BookRoute: typeof BookRoute
  BookingsRoute: typeof BookingsRoute
  CalendarRoute: typeof CalendarRoute
  ConnectRoute: typeof ConnectRouteWithChildren
  InviteRoute: typeof InviteRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PackagesRoute: typeof PackagesRoute
  PaymentsRoute: typeof PaymentsRoute
  PlatformRoute: typeof PlatformRoute
  PortalRoute: typeof PortalRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetRoute: typeof ResetRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/setup': {
      id: '/billing/setup'
      path: '/setup'
      fullPath: '/billing/setup'
      preLoaderRoute: typeof BillingSetupRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof BillingRoute
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/refresh/$businessId': {
      id: '/connect/refresh/$businessId'
      path: '/refresh/$businessId'
      fullPath: '/connect/refresh/$businessId'
      preLoaderRoute: typeof ConnectRefreshBusinessIdRouteImport
      parentRoute: typeof ConnectRoute
    }
    '/connect/return/$businessId': {
      id: '/connect/return/$businessId'
      path: '/return/$businessId'
      fullPath: '/connect/return/$businessId'
      preLoaderRoute: typeof ConnectReturnBusinessIdRouteImport
      parentRoute: typeof ConnectRoute
    }
  }
}

interface BillingRouteChildren {
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSetupRoute: typeof BillingSetupRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  BillingIndexRoute: typeof BillingIndexRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingCancelRoute: BillingCancelRoute,
  BillingSetupRoute: BillingSetupRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  BillingIndexRoute: BillingIndexRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface ConnectRouteChildren {
  ConnectRefreshBusinessIdRoute: typeof ConnectRefreshBusinessIdRoute
  ConnectReturnBusinessIdRoute: typeof ConnectReturnBusinessIdRoute
}

const ConnectRouteChildren: ConnectRouteChildren = {
  ConnectRefreshBusinessIdRoute: ConnectRefreshBusinessIdRoute,
  ConnectReturnBusinessIdRoute: ConnectReturnBusinessIdRoute,
}

const ConnectRouteWithChildren =
  ConnectRoute._addFileChildren(ConnectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRouteWithChildren,
  BookRoute: BookRoute,
  BookingsRoute: BookingsRoute,
  CalendarRoute: CalendarRoute,
  ConnectRoute: ConnectRouteWithChildren,
  InviteRoute: InviteRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PackagesRoute: PackagesRoute,
  PaymentsRoute: PaymentsRoute,
  PlatformRoute: PlatformRoute,
  PortalRoute: PortalRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetRoute: ResetRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
